### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by kemjones** [differentpla-net/differentpla-net.github.io#1]
"https://blogs.msdn.microsoft.com/oldnewthing/20050128-00/?p=36573/" contains this text:

Sometimes people go to great lengths to get information which is available in a much simpler way. We saw it a few days ago when we found a 200+-line C# program that could be replaced with a 90-byte batch file. Here’s another example of a rather roundabout way of capturing the current directory from a batch file.
---
The phrase "of capturing the current directory from a batch file" links here "http://www.differentpla.net/node/view/255" which yields:

The page you were looking for does not exist, or (more likely) you've been struck down by dreaded link-rot.

File an issue here, and I'll fix it as soon as possible.
---
Clicking the link "here" brings me to this page.

**Comment by kemjones** [comment]
I was struck down with the dreaded link-rot...

**Comment by rlipscombe** [comment]
Should be fixed now (but I can't try it myself because of internal/external DNS issues here).
