### ISSUE TITLE
Dead link and license question

### ISSUE THREAD

**Issue by jreederHON** [differentpla-net/differentpla-net.github.io#4]
The link in Readme.MD on https://github.com/rlipscombe/bouncy-castle-csharp is link-rotted.

Also, I'm interested in using some of the bouncy-castle-csharp for creating certificates, but you don't have a license specified. Would you be willing to specify one for your GitHub project?

Thanks,
Jeff

**Comment by rlipscombe** [comment]
Fixed; http://blog.differentpla.net/blog/2013/03/18/using-bouncy-castle-from-net
