### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by andynormancx** [differentpla-net/differentpla-net.github.io#5]
Tom has got the riocar.org FAQ site up and running again.

It tries to link to http://www.differentpla.net/node/view/387, promising "Roger Lipscombe has prepared an excellent guide to the song file structure".

The link is sadly dead...

I can't find a likely matching post on your current blog.

**Comment by rlipscombe** [comment]
It's probably http://blog.differentpla.net/blog/2005/02/13/empeg-file-structures/. I could put a jekyll-redirect-from link in, but I'd want to see the context first.

**Comment by andynormancx** [comment]
It is linked from http://riocar.org/Developer_Info/15.html

**Comment by rlipscombe** [comment]
Should be fixed now; just waiting for GH pages to rebuild...

**Comment by rlipscombe** [comment]
Hope you had a good Christmas, btw.

**Comment by andynormancx** [comment]
Awesome. Had a great Christmas thanks, hopefully we'll get to catch up this year...

Just been looking at Jekyll for a new blog I was thinking of starting.

**Comment by rlipscombe** [comment]
This was fixed; forgot to close it.
