### ISSUE TITLE
Downloading from an HTTP Server using WinInet - dead link

### ISSUE THREAD

**Issue by BockarooZ** [differentpla-net/differentpla-net.github.io#6]
Greetings Roger!

Was attempting to look over the code linked to the following blog post. But the link is dead.

http://blog.differentpla.net/blog/2004/02/26/downloading-from-an-http-server-using-wininet/

Any chance it's sill floating around somewhere?

Many thanks,

Mark Zipkin
Philadelphia, Pennsylvania, USA

**Comment by rlipscombe** [comment]
There's a bunch of related code here: https://github.com/rlipscombe/snopilot/tree/master/apps/PostFile

**Comment by rlipscombe** [comment]
Fixed (finally) in commit 26a57cacca9e9573341a9e43fc9dd7795fdba27b. I found a USB stick in a drawer with the source code on it.
